FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD your_mysql_root_password

ENV MYSQL_DATABASE your_mysql_database
ENV MYSQL_USER your_mysql_user
ENV MYSQL_PASSWORD your_mysql_user_password

COPY my.cnf /etc/mysql/conf.d/

EXPOSE 3306
